mysql_host: 192.168.42.71
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30663035383236323263363639653064643738366635326133363764383061396665356339383439
          3939663339343239373539613331303933323037303564370a613532323965613735656330323561
          30383464353864396634356339323361366134646337383734643261363664643633316130613062
          3133363866376238330a313737633935616333643031646135636639316631303232313232366263
          3063
dedicated_exporter_group: exporters
dedicated_exporter_user: exporter
mysql_exporter_user: mysql_exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66353037303565353966306537303339653832343031313761316666663163646135396565373037
          6235356238653934633134323965346538303762383561340a316364336531343835636133656664
          32366364643632363761313830383466643339626166616462646232383066653962363737313161
          6262653831306336340a323265656333653539623736313331633836316236623962326333653864
          3034
backup_mysql_username: backup
backup_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32383034633034316338623336323936633833383337396438383761663032636262333464666662
          6536303631383236393364323039356632313161653131320a356536316636366262313665323239
          32613034333439396266616636626362363034646366343933393935653737383334653664663230
          6364626261356634310a333036373365376434353639353865643064376164393231653935343938
          3537
replication_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63376135343764346539363438616565333763303266666232306134323662313764386165333732
          6464326136333566616238646332326235346264613835310a313935333066326239306132393533
          32383938336536663231333232353461373530353435633738633235346165373766653764336565
          3666343936353265610a346461306130633936343430656534356162383761623131613438353464
          6438
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.42.0/24
  - 127.0.0.0/8
  - 172.17.0.0/16
records:
  - type: NS
    entries:
      - name: skaldr.io.
        address: vm01.skaldr.io.
      - name: skaldr.io.
        address: vm02.skaldr.io.
      - name: skaldr.io.
        address: influxdb.skaldr.io.
  - type: A
    entries:
      - name: vm01.skaldr.io.
        address: 192.168.42.124
      - name: vm02.skaldr.io.
        address: 192.168.42.71
      - name: influxdb.skaldr.io.
        address: 192.168.42.124
      - name: backup.skaldr.io.
        address: 192.168.42.156

vm01_internal_ip: 192.168.42.124
vm02_internal_ip: 192.168.42.71

slave_internal_ip: 192.168.42.71
grafana_port: 12480

pinger_username: pinger
pinger_group: admin

domain: skaldr.io
github_user: anhhungggg
backup_server_ip_address: 192.168.42.156

grafana_docker_port: 3001
agama_docker_port: 8001
