mysql_host: 192.168.42.120
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30663035383236323263363639653064643738366635326133363764383061396665356339383439
          3939663339343239373539613331303933323037303564370a613532323965613735656330323561
          30383464353864396634356339323361366134646337383734643261363664643633316130613062
          3133363866376238330a313737633935616333643031646135636639316631303232313232366263
          3063
dedicated_exporter_group: exporters
dedicated_exporter_user: exporter
mysql_exporter_user: mysql_exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66353037303565353966306537303339653832343031313761316666663163646135396565373037
          6235356238653934633134323965346538303762383561340a316364336531343835636133656664
          32366364643632363761313830383466643339626166616462646232383066653962363737313161
          6262653831306336340a323265656333653539623736313331633836316236623962326333653864
          3034
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.42.0/24
  - 127.0.0.0/8
records:
  - type: NS
    entries:
      - name: skaldr.io.
        address: vm01.skaldr.io.
      - name: skaldr.io.
        address: vm02.skaldr.io.
      - name: skaldr.io.
        address: influxdb.skaldr.io.
  - type: A
    entries:
      - name: vm01.skaldr.io.
        address: 192.168.42.136
      - name: vm02.skaldr.io.
        address: 192.168.42.120
      - name: influxdb.skaldr.io.
        address: 192.168.42.136

vm01_internal_ip: 192.168.42.136
vm02_internal_ip: 192.168.42.120

slave_internal_ip: 192.168.42.120
grafana_port: 13680

pinger_username: pinger
pinger_group: admin

domain: skaldr.io
