mysql_host: 192.168.42.20
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30663035383236323263363639653064643738366635326133363764383061396665356339383439
          3939663339343239373539613331303933323037303564370a613532323965613735656330323561
          30383464353864396634356339323361366134646337383734643261363664643633316130613062
          3133363866376238330a313737633935616333643031646135636639316631303232313232366263
          3063
dedicated_exporter_group: exporters
dedicated_exporter_user: exporter
mysql_exporter_user: mysql_exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66353037303565353966306537303339653832343031313761316666663163646135396565373037
          6235356238653934633134323965346538303762383561340a316364336531343835636133656664
          32366364643632363761313830383466643339626166616462646232383066653962363737313161
          6262653831306336340a323265656333653539623736313331633836316236623962326333653864
          3034
backup_mysql_username: backup
backup_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32383034633034316338623336323936633833383337396438383761663032636262333464666662
          6536303631383236393364323039356632313161653131320a356536316636366262313665323239
          32613034333439396266616636626362363034646366343933393935653737383334653664663230
          6364626261356634310a333036373365376434353639353865643064376164393231653935343938
          3537
replication_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63376135343764346539363438616565333763303266666232306134323662313764386165333732
          6464326136333566616238646332326235346264613835310a313935333066326239306132393533
          32383938336536663231333232353461373530353435633738633235346165373766653764336565
          3666343936353265610a346461306130633936343430656534356162383761623131613438353464
          6438
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.42.0/24
  - 127.0.0.0/8
  - 172.17.0.0/16
records:
  - type: NS
    entries:
      - name: skaldr.io.
        address: vm01.skaldr.io.
      - name: skaldr.io.
        address: vm02.skaldr.io.
      - name: skaldr.io.
        address: vm03.skaldr.io.
      - name: skaldr.io.
        address: influxdb.skaldr.io.
  - type: A
    entries:
      - name: vm01.skaldr.io.
        address: 192.168.42.44
      - name: vm02.skaldr.io.
        address: 192.168.42.20
      - name: vm03.skaldr.io.
        address: 192.168.42.85
      - name: influxdb.skaldr.io.
        address: 192.168.42.44
      - name: backup.skaldr.io.
        address: 192.168.42.156

vm01_internal_ip: 192.168.42.44
vm02_internal_ip: 192.168.42.20
vm03_internal_ip: 192.168.42.85

slave_internal_ip: 192.168.42.20
grafana_port: 12088

pinger_username: pinger
pinger_group: admin

domain: skaldr.io
github_user: anhhungggg
backup_server_ip_address: 192.168.42.156

grafana_docker_port: 3001
agama_docker_port: 8081

agama_container_per_vm: 1
dns_transfer_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38656662663031656337303766663362306531366137653031616536633533613362356361623135
          6664336333623231333336666631663630336135386531360a376531623833633063353161353061
          30636337373931313138653533333331653931313030363762613239633033613433633363313236
          3363376165323333370a373636653464326565616364383930376663393161363433326436663336
          62303738663733316662626166323431643661396338633935333062336562373662656336303632
          6634393935303936386335376635383865646234393866336637

dns_update_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33336536393737386530373630306630343666396534663332303239366335616466306338636666
          6161373537306262393465383032633361353338313166620a636539363338656333663631386538
          66396666313638656561323663306238316339376531306435633365623762643165636464366635
          3935353833353737630a326366346433376330363737393132363937316162623564383766623865
          34666535333033383736346263636466376138623538316134313333666436663335376664303438
          3763633235363361323732663836633564663563373933343835
