mysql_host: 192.168.42.123
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30663035383236323263363639653064643738366635326133363764383061396665356339383439
          3939663339343239373539613331303933323037303564370a613532323965613735656330323561
          30383464353864396634356339323361366134646337383734643261363664643633316130613062
          3133363866376238330a313737633935616333643031646135636639316631303232313232366263
          3063
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.42.0/24
  - 127.0.0.0/8
records:
  - type: NS
    entries:
      - name: skaldr.io.
        address: vm01.skaldr.io.
      - name: skaldr.io.
        address: vm02.skaldr.io.
  - type: A
    entries:
      - name: vm01.skaldr.io.
        address: 192.168.42.123
      - name: vm02.skaldr.io.
        address: 192.168.42.28
