- name: make sure nginx is installed
  become: yes
  apt:
    name: nginx
    state: present

- name: open endpoint for stub_status
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: make sure dedicated group existed
  become: yes
  group:
    name: "{{dedicated_exporter_group}}"
    state: present
    system: yes

- name: make sure dedicated user existed
  become: yes
  user:
    name: "{{dedicated_exporter_user}}"
    group: "{{dedicated_exporter_group}}"
    shell: /sbin/nologin

- name: check that the nginx_exporter exists
  stat:
    path: /opt/nginx-prometheus-exporter-0.8.0-linux-amd64.tar.gz
  register: stat_result

- name: download nginx_exporter
  become: yes
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.8.0/nginx-prometheus-exporter-0.8.0-linux-amd64.tar.gz
    dest: /opt/
  when: stat_result.stat.exists == False

- name: create repo for nginx_exporter
  become: yes
  file:
    path: /opt/nginx_exporter
    state: directory
    mode: '0755'

- name: untar
  become: yes
  unarchive:
    src: /opt/nginx-prometheus-exporter-0.8.0-linux-amd64.tar.gz
    dest: /opt/nginx_exporter/
    remote_src: yes

- name: systemd nginx_exporter
  become: yes
  template:
    src:  nginx_prometheus_exporter.service.j2
    dest: /etc/systemd/system/nginx_prometheus_exporter.service
  notify:
    - daemon reload
    - restart nginx_exporter
    - hash

- name: start nginx_exporter
  become: yes
  service:
    name: nginx_prometheus_exporter
    state: started
